// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_available_dates from "./routes/api/available-dates.ts";
import * as $api_menu from "./routes/api/menu.ts";
import * as $api_orders from "./routes/api/orders.ts";
import * as $index from "./routes/index.tsx";
import * as $OrderForm from "./islands/OrderForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/available-dates.ts": $api_available_dates,
    "./routes/api/menu.ts": $api_menu,
    "./routes/api/orders.ts": $api_orders,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/OrderForm.tsx": $OrderForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
